apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-l2hl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-l2hl
    app.kubernetes.io/part-of: image-repository-cr-dotnet-component
  name: devfile-sample-dotnet60-basic-l2hl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: devfile-sample-dotnet60-basic-l2hl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: devfile-sample-dotnet60-basic-l2hl
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rs-demos-flna-tenant/image-repository-cr-dotnet-component/devfile-sample-dotnet60-basic-l2hl@sha256:1b04da90deae3b3324bdc490bbb100c84a6d8cab48b8ce3d1430f29b59c5951f
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
