apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dotnet60-basic-l2hl
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/redhat-appstudio-qe/rs-demos-flna-tenant/image-repository-cr-dotnet-component/devfile-sample-dotnet60-basic-l2hl@sha256:1b04da90deae3b3324bdc490bbb100c84a6d8cab48b8ce3d1430f29b59c5951f
        name: main
        resources: {}
status: {}
